[package]
name = "pseudo_random"
version = "0.1.0"
edition = "2021"
authors = ["n514 n5ive1ne4our@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
